/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-04-27 18:31:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>My School Education Category Bootstrap Responsive website Template | Register :: w3layouts</title>\r\n");
      out.write("    <!-- Meta tag Keywords -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"keywords\" content=\"My School Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("    <script>\r\n");
      out.write("        addEventListener(\"load\", function () {\r\n");
      out.write("			setTimeout(hideURLbar, 0);\r\n");
      out.write("		}, false);\r\n");
      out.write("\r\n");
      out.write("		function hideURLbar() {\r\n");
      out.write("			window.scrollTo(0, 1);\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("    <!-- //Meta tag Keywords -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom-Files -->\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("    <!-- Bootstrap-CSS -->\r\n");
      out.write("    <link href=\"css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("    <!-- Style-CSS -->\r\n");
      out.write("    <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font-Awesome-Icons-CSS -->\r\n");
      out.write("    <!-- //Custom-Files -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Web-Fonts -->\r\n");
      out.write("    <link href=\"//fonts.googleapis.com/css?family=Lora:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"//fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800&amp;subset=latin-ext\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- //Web-Fonts -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- header -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header d-lg-flex justify-content-between align-items-center py-2 px-sm-2 px-1\">\r\n");
      out.write("                <!-- logo -->\r\n");
      out.write("                <div id=\"logo\">\r\n");
      out.write("                    <h1><a href=\"index.jsp\">My School</a></h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- //logo -->\r\n");
      out.write("                <!-- nav -->\r\n");
      out.write("                <div class=\"nav_w3ls ml-lg-5\">\r\n");
      out.write("                    <nav>\r\n");
      out.write("                        <label for=\"drop\" class=\"toggle\">Menu</label>\r\n");
      out.write("                        <input type=\"checkbox\" id=\"drop\" />\r\n");
      out.write("                        <ul class=\"menu\">\r\n");
      out.write("                            <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("                            <li><a href=\"index.jsp\">About</a></li>\r\n");
      out.write("                            <li><a href=\"index.jsp\">Join Now</a></li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <!-- First Tier Drop Down -->\r\n");
      out.write("                                <label for=\"drop-2\" class=\"toggle toogle-2\">Pages <span class=\"fa fa-angle-down\"\r\n");
      out.write("                                        aria-hidden=\"true\"></span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <a href=\"#\">Pages <span class=\"fa fa-angle-down\" aria-hidden=\"true\"></span></a>\r\n");
      out.write("                                <input type=\"checkbox\" id=\"drop-2\" />\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"index.jsp\" class=\"drop-text\">Events</a></li>\r\n");
      out.write("                                    <li><a href=\"index.jsp\" class=\"drop-text\">What We Do?</a></li>\r\n");
      out.write("                                    <li><a href=\"index.jsp\" class=\"drop-text\">Popular Courses</a></li>\r\n");
      out.write("                                    <li><a href=\"index.jsp\" class=\"drop-text\">Statistics</a></li>\r\n");
      out.write("                                    <li><a href=\"index.jsp\" class=\"drop-text\">Gallery</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"index.jsp\">Contact</a></li>\r\n");
      out.write("                            <li><a href=\"login.html\">Login</a></li>\r\n");
      out.write("                            <li><a href=\"register.html\">Register</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- //nav -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- //header -->\r\n");
      out.write("\r\n");
      out.write("    <!-- inner banner -->\r\n");
      out.write("    <div class=\"inner-banner-w3ls py-5\" id=\"home\">\r\n");
      out.write("        <div class=\"container py-xl-5 py-lg-3\">\r\n");
      out.write("            <!-- register  -->\r\n");
      out.write("            <div class=\"modal-body mt-md-2 mt-5\">\r\n");
      out.write("                <h3 class=\"title-w3 mb-5 text-center text-wh font-weight-bold\">Register Now</h3>\r\n");
      out.write("                <form action=\"StudentController\" method=\"post\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-form-label\">First name</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"your First name\" name=\"fname\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-form-label\">Last name</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"your Last name\" name=\"lname\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-form-label\">Email</label>\r\n");
      out.write("                        <input type=\"email\" class=\"form-control\" placeholder=\"gaurang@email.com\" name=\"email\"\r\n");
      out.write("                            required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-form-label\">Mobile</label>\r\n");
      out.write("                        <input type=\"tel\" class=\"form-control\" placeholder=\"1234567890\" name=\"mobile\"\r\n");
      out.write("                            required=\"\" min=\"10\" maxlength=\"10\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-form-label\">Gender</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Male/Female\" name=\"gender\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-form-label\">Password</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" placeholder=\"*****\" name=\"password\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn button-style-w3\" value=\"register\" name=\"action\">Register</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //register -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //inner banner -->\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <!-- copyright -->\r\n");
      out.write("    <div class=\"copyright-w3ls py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <!-- copyright -->\r\n");
      out.write("                <p class=\"col-lg-8 copy-right-grids text-wh text-lg-left text-center mt-lg-2\">© 2023 Tops Technologies School. All\r\n");
      out.write("                    Rights Reserved | Design by\r\n");
      out.write("                    <a href=\"https://github.com/Gaurangdalvadi6\" target=\"_blank\">Mr_Rambo_King</a>\r\n");
      out.write("                </p>\r\n");
      out.write("                <!-- //copyright -->\r\n");
      out.write("                <!-- social icons -->\r\n");
      out.write("                <div class=\"col-lg-4 w3social-icons text-lg-right text-center mt-lg-0 mt-3\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"rounded-circle\">\r\n");
      out.write("                                <span class=\"fa fa-facebook-f\"></span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"px-2\">\r\n");
      out.write("                            <a href=\"#\" class=\"rounded-circle\">\r\n");
      out.write("                                <span class=\"fa fa-google-plus\"></span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"rounded-circle\">\r\n");
      out.write("                                <span class=\"fa fa-twitter\"></span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"pl-2\">\r\n");
      out.write("                            <a href=\"#\" class=\"rounded-circle\">\r\n");
      out.write("                                <span class=\"fa fa-dribbble\"></span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- //social icons -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //copyright -->\r\n");
      out.write("    <!-- move top icon -->\r\n");
      out.write("    <a href=\"#home\" class=\"move-top text-center\">\r\n");
      out.write("        <span class=\"fa fa-angle-double-up\" aria-hidden=\"true\"></span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <!-- //move top icon -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
